package fr.oms.dataloader;

public class JSONTags {
	public static String FICHIER_ACTUS = "actus.json";
	public static String FICHIER_EVENTS = "evenements.json";
	public static String FICHIER_ASSOCS = "associations.json";
	public static String FICHIER_EQUIPS = "equipements.json";
	public static String RESULT = "result";
	public static String IDENTIFIER = "identifier";
	public static String CREATED = "created";
	public static String TITLE = "title";
	public static String BODY = "body";
	public static String IMAGE = "image";
	public static String ASSOCIATION = "association";
	public static String LOCATION_01 = "location01";
	public static String LOCATION_02 = "location02";
	public static String DATE = "date";
	public static String QUARTIER = "district";
	public static String NATURE = "nature";
	public static String GEOLOC = "geoloc";
	public static String ADDRESS = "address";
	public static String CODE_POSTAL = "postalcode";
	public static String VILLE = "city";
	public static String TEL = "tel";
	public static String GEO_NAME = "name";
	public static String GEO_RUE = "street";
	public static String GEO_VILLE = "city";
	public static String GEO_PROVINCE = "province";
	public static String GEO_POSTAL = "postal_code";
	public static String GEO_PAYS = "country";
	public static String GEO_LONGITUDE = "longitude";
	public static String GEO_LATITUDE = "latitude";
	public static String OMS_MEMBER = "is_oms_member";
	public static String HOURS = "hours";
	public static String DISCIPLINES = "disciplines";
	public static String CONTACT_TITLE="contact_title";
	public static String CONTACT_NOM ="contact_lastname";
	public static String CONTACT_PRENOM="contact_firstname";
	public static String CONTACT_ADDRESS_01="contact_address01";
	public static String CONTACT_ADDRESS_02="contact_address02";
	public static String CONTACT_CODE_POSTAL="contact_postalcode";
	public static String CONTACT_TEL="contact_tel";
	public static String CONTACT_VILLE="contact_city";
	public static String CONTACT_TEL_MOBILE="contact_tel_mobile";
	public static String CONTACT_MAIL="contact_mail";
	public static String CONTACT_WEBSITE="contact_website";
}
